name: eliud_pkg_notifications
description: Eliud package for notifications
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
