---
name: eliud_pkg_notifications
description: Eliud package for notifications
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_notifications
version: 1.0.1+5
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  equatable: ^2.0.5
  cloud_firestore: ^4.6.0
  intl: ^0.18.1
  datetime_picker_formfield: ^2.0.0
  meta: ^1.8.0
  http: ^0.13.5
  eliud_core: ^1.0.4+16
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: 1.0.4+1
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
